export const cars = [
    {
        id: '1',
        name: 'Koenigsegg',
        image: '/car1.png',
        price: '$99.00/day',
        type: 'Sport',
        oldPrice: '',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification.svg   ',
    },
    {
        id: '2',
        name: 'Nissan GT - R',
        image: '/car (2).png',
        price: '$80.00/day',
        type: 'Sport',
        oldPrice: '$100.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification (1).svg',
    },
    {
        id: '3',
        name: 'Rolls - Royce',
        image: '/Car (3).png',
        price: '$96.00/day',
        type: 'Sedan',
        oldPrice: '',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification (2).svg',
    },
    {
        id: '4',
        name: 'Nissan GT - R',
        image: '/Car (4).png',
        price: '$80.00/day',
        type: 'Sport',
        oldPrice: '$100.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification (3).svg',
    },
    {
        id: '5',
        name: 'All New Rush',
        image: '/Car (5).png',
        price: '$72.00/day',
        type: 'SUV',
        oldPrice: '$80.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification5.svg',
    },
    {
        id: '6',
        name: 'CR - V',
        image: '/Car (6).png',
        price: '$80.00/day',
        type: 'SUV',
        oldPrice: '',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification6.svg',
    },
    {
        id: '7',
        name: 'All New Terios',
        image: '/Car (7).png',
        price: '$74.00/day',
        type: 'SUV',
        oldPrice: '',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification7.svg',
    },
    {
        id: '8',
        name: 'CR - V',
        image: '/Car (8).png',
        price: '$80.00/day',
        type: 'SUV',
        oldPrice: '',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification6.svg',
    },
    {
        id: '9',
        name: 'MG ZX Exclucive',
        image: '/Car (9).png',
        price: '$76.00/day',
        type: 'Hatchback',
        oldPrice: '$80.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification7.svg',
    },
    {
        id: '10',
        name: 'New MG ZS',
        image: '/Car (10).png',
        price: '$80.00/day',
        type: 'SUV',
        oldPrice: '',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification5.svg',
    },
    {
        id: '11',
        name: 'MG ZX Excite',
        image: '/Car (11).png',
        price: '$74.00/day',
        type: 'Hatchback',
        oldPrice: '',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification6.svg',
    },
    {
        id: '12',
        name: 'New MG ZS',
        image: '/Car (12).png',
        price: '$80.00/day',
        type: 'SUV',
        oldPrice: '',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification (2).svg',
    },
    {
        id: '13',
        name: 'Toyota Corolla',
        image: '/car1.png',
        price: '$68.00/day',
        type: 'Sedan',
        oldPrice: '$75.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification (3).svg',
    },
    {
        id: '14',
        name: 'Honda Civic RS',
        image: '/car (2).png',
        price: '$73.00/day',
        type: 'Sedan',
        oldPrice: '$81.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification5.svg',
    },
    {
        id: '15',
        name: 'Hyundai Elantra',
        image: '/Car (3).png',
        price: '$70.00/day',
        type: 'Sedan',
        oldPrice: '$77.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification6.svg',
    },
    {
        id: '16',
        name: 'Kia Sportage',
        image: '/Car (4).png',
        price: '$84.00/day',
        type: 'SUV',
        oldPrice: '$92.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification7.svg',
    },
    {
        id: '17',
        name: 'Mazda CX - 5',
        image: '/Car (5).png',
        price: '$86.00/day',
        type: 'SUV',
        oldPrice: '$94.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification.svg',
    },
    {
        id: '18',
        name: 'Ford Mustang',
        image: '/Car (6).png',
        price: '$109.00/day',
        type: 'Sport',
        oldPrice: '$121.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification (1).svg',
    },
    {
        id: '19',
        name: 'Chevrolet Camaro',
        image: '/Car (7).png',
        price: '$106.00/day',
        type: 'Coupe',
        oldPrice: '$118.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification (2).svg',
    },
    {
        id: '20',
        name: 'BMW 320i',
        image: '/Car (8).png',
        price: '$98.00/day',
        type: 'Luxury',
        oldPrice: '$110.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification (3).svg',
    },
    {
        id: '21',
        name: 'Mercedes C200',
        image: '/Car (9).png',
        price: '$104.00/day',
        type: 'Luxury',
        oldPrice: '$116.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification5.svg',
    },
    {
        id: '22',
        name: 'Audi A4',
        image: '/Car (10).png',
        price: '$102.00/day',
        type: 'Sedan',
        oldPrice: '$113.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification6.svg',
    },
    {
        id: '23',
        name: 'Lexus RX 350',
        image: '/Car (11).png',
        price: '$114.00/day',
        type: 'SUV',
        oldPrice: '$126.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification7.svg',
    },
    {
        id: '24',
        name: 'Volvo XC60',
        image: '/Car (12).png',
        price: '$101.00/day',
        type: 'SUV',
        oldPrice: '$112.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification.svg',
    },
    {
        id: '25',
        name: 'Skoda Kodiaq',
        image: '/car1.png',
        price: '$83.00/day',
        type: 'SUV',
        oldPrice: '$91.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification (1).svg',
    },
    {
        id: '26',
        name: 'Volkswagen Golf',
        image: '/car (2).png',
        price: '$71.00/day',
        type: 'Hatchback',
        oldPrice: '$79.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification (2).svg',
    },
    {
        id: '27',
        name: 'Peugeot 3008',
        image: '/Car (3).png',
        price: '$82.00/day',
        type: 'Crossover',
        oldPrice: '$90.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification (3).svg',
    },
    {
        id: '28',
        name: 'Renault Megane',
        image: '/Car (4).png',
        price: '$69.00/day',
        type: 'Hatchback',
        oldPrice: '$76.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification5.svg',
    },
    {
        id: '29',
        name: 'Subaru Forester',
        image: '/Car (5).png',
        price: '$85.00/day',
        type: 'SUV',
        oldPrice: '$93.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification6.svg',
    },
    {
        id: '30',
        name: 'Jeep Wrangler',
        image: '/Car (6).png',
        price: '$95.00/day',
        type: 'SUV',
        oldPrice: '$105.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification7.svg',
    },
    {
        id: '31',
        name: 'Toyota Hilux',
        image: '/Car (7).png',
        price: '$92.00/day',
        type: 'Pickup',
        oldPrice: '$101.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification.svg',
    },
    {
        id: '32',
        name: 'Ford Ranger',
        image: '/Car (8).png',
        price: '$90.00/day',
        type: 'Pickup',
        oldPrice: '$99.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification (1).svg',
    },
    {
        id: '33',
        name: 'Kia Carnival',
        image: '/Car (9).png',
        price: '$88.00/day',
        type: 'Van',
        oldPrice: '$97.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification (2).svg',
    },
    {
        id: '34',
        name: 'Mercedes V - Class',
        image: '/Car (10).png',
        price: '$121.00/day',
        type: 'Van',
        oldPrice: '$133.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification (3).svg',
    },
    {
        id: '35',
        name: 'Tesla Model 3',
        image: '/Car (11).png',
        price: '$99.00/day',
        type: 'Electric',
        oldPrice: '$109.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification (2).svg',
    },
    {
        id: '36',
        name: 'Toyota Prius',
        image: '/Car (12).png',
        price: '$78.00/day',
        type: 'Hybrid',
        oldPrice: '$86.00',
        isFavorite: false,
        favoriteIcon: '',
        features: '/Spesification (3).svg',
    },
]
